CREATE DATABASE  IF NOT EXISTS `dynamics.erp` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `dynamics.erp`;
-- MySQL SQL Script for create a schema dynamics.erp 10.13  Distrib 5.6.24, for Win32 (x86)
-- Schema: dynamics.erp -- Data Schema for Dynamics ERP software and Web Apps
--
-- Host: localhost    Database: dynamics.erp
-- ------------------------------------------------------
-- Server version	5.5.5-10.3.12-MariaDB-log

-- 40101 SET @OLD.CHARACTER.SET.CLIENT=@@CHARACTER.SET.CLIENT */
-- 40101 SET @OLD.CHARACTER.SET.RESULTS=@@CHARACTER.SET.RESULTS */
-- 40101 SET @OLD.COLLATION.CONNECTION=@@COLLATION.CONNECTION */
-- 40101 SET NAMES utf8 */
-- 40103 SET @OLD.TIME.ZONE=@@TIME.ZONE */
-- 40103 SET TIME.ZONE=`+00:00` */
-- 40014 SET @OLD.UNIQUE.CHECKS=@@UNIQUE.CHECKS, UNIQUE.CHECKS=0 */
-- 40014 SET @OLD.FOREIGN.KEY.CHECKS=@@FOREIGN.KEY.CHECKS, FOREIGN.KEY.CHECKS=0 */
-- 40101 SET @OLD.SQL.MODE=@@SQL.MODE, SQL.MODE=`NO.AUTO.VALUE.ON.ZERO` */
-- 40111 SET @OLD.SQL.NOTES=@@SQL.NOTES, SQL.NOTES=0 */

--
-- Table structure for table `dynerp.ajuste`
--

DROP TABLE IF EXISTS `dynerp.ajuste`;
CREATE TABLE `dynerp.ajuste` (
	`ajuste.ajue.num`	int 		NOT NULL	COMMENT 'Ajuste de Facturas',
	`ajuste.fecha` 		datetime 	NOT NULL	COMMENT 'Fecha del Ajsute',
	`ajuste.motivo` 	varchar(80) NOT NULL	COMMENT 'Motivo del Ajuste',
	`ajuste.total` 		double 		NOT NULL 	COMMENT 'Monto Total Ajuste',
	`ajuste.seriales`	int 		NOT NULL 	COMMENT 'Seriales del Ajuste',
	`ajuste.feccom` 	datetime	NOT NULL 	COMMENT 'Fecha del Comprobante de Ajuste',
	`ajuste.numcom` 	int 		NOT NULL 	COMMENT 'Numero del Comprobante de Ajuste',
	`ajuste.tasa` 		double 		NOT NULL 	COMMENT 'Tasa de Ajuste',
	`ajuste.moneda` 	varchar(06) NOT NULL 	COMMENT 'Moneda (Currency) del Ajuste',
	`ajuste.dis.cen`	text 		NOT NULL 	COMMENT 'Ajuste distribuido',
	`ajuste.campo1` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 1',
	`ajuste.campo2` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 2',
	`ajuste.campo3` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 3',
	`ajuste.campo4` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 4',
	`ajuste.campo5` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 5',
	`ajuste.campo6` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 6',
	`ajuste.campo7` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 7',
	`ajuste.campo8` 	varchar(60) NOT NULL 	COMMENT 'Campo Utility 8',
	`ajuste.co.us.ad` 	varchar(06) NOT NULL 	COMMENT 'Usuario Generador de Ajuste',
	`ajuste.fe.us.ad` 	datetime 	NOT NULL 	COMMENT 'Fecha de Adicion del Ajuste',
	`ajuste.co.us.up` 	varchar(06) NOT NULL 	COMMENT 'Usuario que modifica el Ajuste',
	`ajuste.fe.us.up` 	datetime 	NOT NULL 	COMMENT 'Fecha de Modificacion del Ajuste',
	`ajuste.co.us.de` 	varchar(06) NOT NULL 	COMMENT 'Usuario que elimina el Ajsute',
	`ajuste.fe.us.de` 	datetime 	NOT NULL 	COMMENT 'Fecha de Eliminacion del Ajuste',
	`ajuste.revisado` 	char(01) 	NOT NULL 	COMMENT 'Ajuste Revisado (S/N)',
	`ajuste.trasnfe` 	char(01) 	NOT NULL 	COMMENT 'Ajuste Transferido (S/N)',
	`ajuste.cod.suc` 	char(06) 	NOT NULL 	COMMENT 'Codigo Sucursal',
	`ajuste.anulada` 	bit 		NOT NULL 	COMMENT 'Ajuste Anulado (0/1)',
	`ajuste.aux01` 		double 		NOT NULL 	COMMENT 'Monto Auxiliar Ajuste',
	`ajuste.aux02` 		varchar(30) NOT NULL 	COMMENT 'Descripcion Auxiliar Ajuste',
	`ajuste.imp.num` 	int 		NOT NULL 	COMMENT 'Num Comprobante de ISLR Ajuste',
	`ajuste.fact.num` 	int 		NOT NULL 	COMMENT 'Num Factura aplicado el Ajuste',  
	PRIMARY KEY (`ajuste.ajue.num`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


--
-- Table structure for table `dynerp.almacen`
--

DROP TABLE IF EXISTS `dynerp.almacen`;

CREATE TABLE `dynerp.almacen` (
	`almacen.co.alma` 	char(6) 				COMMENT,
	`almacen.alma.des` 	varchar(60)	NOT NULL	COMMENT,
	`almacen.nro.fact` 	int			NOT NULL 	COMMENT,
	`almacen.fac.ini` 	int 		NOT NULL 	COMMENT,
	`almacen.fac.fad` 	int 		NOT NULL 	COMMENT,
	`almacen.campo1` 	varchar(60)	NOT NULL 	COMMENT,
	`almacen.campo2` 	varchar(60) NOT NULL 	COMMENT,
	`almacen.campo3` 	varchar(60) NOT NULL 	COMMENT,
	`almacen.campo4` 	varchar(60) NOT NULL 	COMMENT,
	`almacen.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`almacen.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`almacen.co.us.mo` 	varchar(06) NOT NULL 	COMMENT,
	`almacen.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`almacen.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`almacen.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`almacen.revisado` 	char(01) 	NOT NULL 	COMMENT,
	`almacen.trasnfe` 	char(01) 	NOT NULL 	COMMENT,
	`almacen.co.sucu` 	char(06) 	NOT NULL 	COMMENT,
	`almacen.nc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ajus.num` 	int 		NOT NULL 	COMMENT,
	`almacen.tras.num` 	int 		NOT NULL 	COMMENT,
	`almacen.fisi.num` 	int 		NOT NULL 	COMMENT,
	`almacen.num.kit` 	int 		NOT NULL 	COMMENT,
	`almacen.genk.num` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ped.num` 	int 		NOT NULL 	COMMENT,
	`almacen.cotc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.devc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ndd.num` 	int 		NOT NULL 	COMMENT,
	`almacen.post.num` 	int 		NOT NULL 	COMMENT,
	`almacen.cfxg.num` 	int 		NOT NULL 	COMMENT,
	`almacen.chdv.num` 	int 		NOT NULL 	COMMENT,
	`almacen.giro.num` 	int 		NOT NULL 	COMMENT,
	`almacen.reten.num` int 		NOT NULL 	COMMENT,
	`almacen.cb.num` 	int 		NOT NULL 	COMMENT,
	`almacen.movb.num` 	int 		NOT NULL 	COMMENT,
	`almacen.movc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ordp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.depc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.comp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ordc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.cotp.num`	int 		NOT NULL 	COMMENT,
	`almacen.devp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ndr.num` 	int 		NOT NULL 	COMMENT,
	`almacen.postppnum` int 		NOT NULL 	COMMENT,
	`almacen.ccxg.num` 	int 		NOT NULL 	COMMENT,
	`almacen.chdvppnum` int 		NOT NULL 	COMMENT,
	`almacen.giroppnum` int 		NOT NULL 	COMMENT,
	`almacen.nccpp.num` int 		NOT NULL 	COMMENT,
	`almacen.ndcpp.num` int 		NOT NULL 	COMMENT,
	`almacen.retppnum` 	int 		NOT NULL 	COMMENT,
	`almacen.pg.num` 	int 		NOT NULL 	COMMENT,
	`almacen.aju.posm` 	int 		NOT NULL 	COMMENT,
	`almacen.aju.posa` 	int 		NOT NULL 	COMMENT,
	`almacen.aju.negm` 	int 		NOT NULL 	COMMENT,
	`almacen.aju.nega` 	int 		NOT NULL 	COMMENT,
	`almacen.aju.posmc` int 		NOT NULL 	COMMENT,
	`almacen.aju.posac` int 		NOT NULL 	COMMENT,
	`almacen.aju.negmc` int 		NOT NULL 	COMMENT,
	`almacen.aju.negac` int 		NOT NULL 	COMMENT,
	`almacen.pventa` 	int 		NOT NULL 	COMMENT,
	`almacen.turnosic` 	int 		NOT NULL 	COMMENT,
	`almacen.plv.num` 	int 		NOT NULL 	COMMENT,
	`almacen.plc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.tabislr` 	int 		NOT NULL 	COMMENT,
	`almacen.imp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.rma.cli` 	int 		NOT NULL 	COMMENT,
	`almacen.rma.prov` 	int 		NOT NULL 	COMMENT,
	`almacen.rma.entc` 	int 		NOT NULL 	COMMENT,
	`almacen.rma.entp` 	int 		NOT NULL 	COMMENT,
	`almacen.rma.regs` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.s1` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.fact.s2` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.fact.s3` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.fact.s4`	char(10) 	NOT NULL 	COMMENT,
	`almacen.fact.s5`	char(10) 	NOT NULL 	COMMENT,
	`almacen.nde.s1` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nde.s2` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nde.s3` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nde.s4` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nde.s5` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nc.s1` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nc.s2` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nc.s3` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nc.s4` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nc.s5` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nd.s1` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nd.s2` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nd.s3` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nd.s4` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.nd.s5` 	char(10) 	NOT NULL 	COMMENT,
	`almacen.fact.f1` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.f2` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.f3` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.f4` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.f1` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.f2` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.f3` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.f4` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.f1` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.f2` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.f3` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.f4` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.f1` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.f2` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.f3` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.f4` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.p1` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.p2` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.p3` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.p4` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.p5` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.p1` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.p2` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.p3` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.p4` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.p5` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.p1` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.p2` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.p3` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.p4` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.p5` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.p1` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.p2` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.p3` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.p4` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.p5` 	int 		NOT NULL 	COMMENT,
	`almacen.fact.num2` int 		NOT NULL 	COMMENT,
	`almacen.fact.num3` int 		NOT NULL 	COMMENT,
	`almacen.fact.num4` int 		NOT NULL 	COMMENT,
	`almacen.fact.num5` int 		NOT NULL 	COMMENT,
	`almacen.nde.num2` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.num3` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.num4` 	int 		NOT NULL 	COMMENT,
	`almacen.nde.num5` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.num2` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.num3` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.num4` 	int 		NOT NULL 	COMMENT,
	`almacen.nc.num5` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.num2` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.num3` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.num4` 	int 		NOT NULL 	COMMENT,
	`almacen.nd.num5` 	int 		NOT NULL 	COMMENT,
	`almacen.serie2` 	bit 		NOT NULL 	COMMENT,
	`almacen.serie3` 	bit 		NOT NULL 	COMMENT,
	`almacen.serie4` 	bit 		NOT NULL 	COMMENT,
	`almacen.serie5` 	bit 		NOT NULL 	COMMENT,
	`almacen.emp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.dmc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.tax.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ced.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ent.num` 	int 		NOT NULL 	COMMENT,
	`almacen.cie.num` 	int 		NOT NULL 	COMMENT,
	`almacen.odp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.req.num` 	int 		NOT NULL 	COMMENT,
	`almacen.dev.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ex1.num` 	int 		NOT NULL 	COMMENT,
	`almacen.inp.num` 	int 		NOT NULL 	COMMENT,
	`almacen.cost.num` 	int 		NOT NULL 	COMMENT,
	`almacen.par.num` 	int 		NOT NULL 	COMMENT,
	`almacen.esc.num` 	int 		NOT NULL 	COMMENT,
	`almacen.pla.num` 	int 		NOT NULL 	COMMENT,
	`almacen.men.num` 	int 		NOT NULL 	COMMENT,
	`almacen.dist.num` 	int 		NOT NULL 	COMMENT,
	`almacen.ex2.num` 	int 		NOT NULL 	COMMENT,
	PRIMARY KEY (`almacen.co.alma`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Almacenes del Sistema`;


DROP TABLE IF EXISTS `dynerp.ambaju`;

CREATE TABLE `dynerp.ambaju` (
	`ambaju.usua` 		char(06) 				COMMENT,
	`ambaju.ajue.num` 	bit 		NOT NULL 	COMMENT,
	`ambaju.moneda` 	bit 		NOT NULL 	COMMENT,
	`ambaju.monedad` 	bit 		NOT NULL 	COMMENT,
	`ambaju.co.mone` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.fecha` 		bit 		NOT NULL 	COMMENT,
	`ambaju.motivo` 	bit 		NOT NULL 	COMMENT,
	`ambaju.bt.ser.ent`	bit 		NOT NULL 	COMMENT,
	`ambaju.bt.ser.sal` bit 		NOT NULL 	COMMENT,
	`ambaju.bt.anulo` 	bit 		NOT NULL 	COMMENT,
	`ambaju.bt.reversa` bit 		NOT NULL 	COMMENT,
	`ambaju.almacen` 	bit 		NOT NULL 	COMMENT,
	`ambaju.almacend`	bit 		NOT NULL 	COMMENT,
	`ambaju.co.alma` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.cantidad` 	bit 		NOT NULL 	COMMENT,
	`ambaju.cantidadd` 	bit 		NOT NULL 	COMMENT,
	`ambaju.stock.act` 	double 		NOT NULL	COMMENT,
	`ambaju.unidad` 	bit 		NOT NULL 	COMMENT,
	`ambaju.costo` 		bit 		NOT NULL 	COMMENT,
	`ambaju.stock.neg` 	bit 		NOT NULL 	COMMENT,
	`ambaju.pstock.neg` bit 		NOT NULL 	COMMENT,
	`ambaju.tamcol01` 	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol02`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol03`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol04`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol05`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol06`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol07`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol08`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol09`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol10`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol11`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol12`  	int 		NOT NULL 	COMMENT,
	`ambaju.tamcol13`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol01`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol02`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol03`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol04`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol05`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol06`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol07`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol08`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol09`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol10`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol11`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol12`  	int 		NOT NULL 	COMMENT,
	`ambaju.poscol13`  	int 		NOT NULL 	COMMENT,
	`ambaju.campo1` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo2` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo3` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo4` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo5` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo6` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo7` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.campo8` 	varchar(60) NOT NULL 	COMMENT,
	`ambaju.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`ambaju.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`ambaju.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`ambaju.co.sucu` 	char(06) 	NOT NULL 	COMMENT,
	`ambaju.p.lotefec` 	bit 		NOT NULL 	COMMENT,
	`ambaju.p.control` 	bit 		NOT NULL 	COMMENT,
 PRIMARY KEY (`ambaju.amb.usua`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Parametros del Sistema`;


DROP TABLE IF EXISTS `dynerp.ambart`;

CREATE TABLE `dynerp.ambart` (
	`ambart.amb.usua`		char(06)	 			NOT NULL	COMMENT,
	`ambart.co.artv` 		bit 		NOT NULL 	COMMENT,
	`ambart.art.desv` 		bit 		NOT NULL 	COMMENT,
	`ambart.fecha.regv` 	bit 		NOT NULL 	COMMENT,
	`ambart.manj.serv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.lind` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.linv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.lad`			char(06) 	NOT NULL 	COMMENT,
	`ambart.co.catd` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.catv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.cat`			char(06) 	NOT NULL 	COMMENT,
	`ambart.co.subld` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.sublv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.subl`		char(06) 	NOT NULL 	COMMENT,
	`ambart.co.colord` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.colorv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.color`		char(06) 	NOT NULL 	COMMENT,
	`ambart.itemv` 			bit 		NOT NULL 	COMMENT,
	`ambart.refv` 			bit 		NOT NULL 	COMMENT,
	`ambart.modelov` 		bit 		NOT NULL 	COMMENT,
	`ambart.procedencd` 	bit 		NOT NULL 	COMMENT,
	`ambart.procedencv` 	bit 		NOT NULL 	COMMENT,
	`ambart.procedenci`		char(06) 	NOT NULL 	COMMENT,
	`ambart.comentariv` 	bit 		NOT NULL 	COMMENT,
	`ambart.co.provd` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.provv` 		bit 		NOT NULL 	COMMENT,
	`ambart.co.prov`		char(10) 	NOT NULL 	COMMENT,
	`ambart.ubicacionv` 	bit 		NOT NULL 	COMMENT,
	`ambart.relac.autd` 	bit 		NOT NULL 	COMMENT,
	`ambart.relac.autv` 	bit 		NOT NULL 	COMMENT,
	`ambart.relac.aut` 		int 		NOT NULL 	COMMENT,
	`ambart.pto.pedidv` 	bit 		NOT NULL 	COMMENT,
	`ambart.bt.aranc` 		bit 		NOT NULL 	COMMENT,
	`ambart.stock.maxv` 	bit 		NOT NULL 	COMMENT,
	`ambart.stock.minv` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.omv` 		bit 		NOT NULL 	COMMENT,
	`ambart.prec.vta1v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.vta2v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.vta3v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.vta4v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.vta5v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.agr1v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.agr2v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.agr3v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.agr4v` 	bit 		NOT NULL 	COMMENT,
	`ambart.prec.agr5v` 	bit 		NOT NULL 	COMMENT,
	`ambart.can.agrv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.marg.minv`		bit 		NOT NULL 	COMMENT,
	`ambart.ult.cost.v`  	bit 		NOT NULL 	COMMENT,
	`ambart.cost.pro.v`  	bit 		NOT NULL 	COMMENT,
	`ambart.cost.merc.v` 	bit 		NOT NULL 	COMMENT,
	`ambart.cost.prov.v` 	bit 		NOT NULL 	COMMENT,
	`ambart.ult.cosdov` 	bit 		NOT NULL 	COMMENT,
	`ambart.cost.unanv`  	bit 		NOT NULL 	COMMENT,
	`ambart.ult.cosomv` 	bit 		NOT NULL 	COMMENT,
	`ambart.cost.proomv` 	bit 		NOT NULL 	COMMENT,
	`ambart.fec.proomv` 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.cosd` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.cosv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.cost` 		char(04) 	NOT NULL 	COMMENT,
	`ambart.mont.comiv` 	bit 		NOT NULL 	COMMENT,
	`ambart.punt.cliv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.punt.prov` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.anuladov` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.impd` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.impv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipo.imp` 		char(01) 	NOT NULL 	COMMENT,
	`ambart.licorv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.picturev` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo2`	 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo3`		 	char(30) 	NOT NULL 	COMMENT,
	`ambart.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo5` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo6` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo7` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.campo8` 		char(30) 	NOT NULL 	COMMENT,
	`ambart.co.us.ad`		char(06) 	NOT NULL 	COMMENT,
	`ambart.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambart.co.us.mo`		char(06) 	NOT NULL 	COMMENT,
	`ambart.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambart.co.us.el`		char(06) 	NOT NULL 	COMMENT,
	`ambart.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambart.revisado` 		char(01) 	NOT NULL 	COMMENT,
	`ambart.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`ambart.co.sucu`		char(06) 	NOT NULL 	COMMENT,
	`ambart.pesov` 			bit 		NOT NULL 	COMMENT,
	`ambart.piev` 			bit 		NOT NULL 	COMMENT,
	`ambart.margen1v` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.margen2v` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.margen3v` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.margen4v` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.margen5v` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.tipod` 			bit 		NOT NULL 	COMMENT,
	`ambart.tipov` 			bit 		NOT NULL 	COMMENT,
	`ambart.tipo` 			char(01) 	NOT NULL 	COMMENT,
	`ambart.lotev` 			bit 		NOT NULL 	COMMENT,
	`ambart.reactivar` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.relacartv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.porc.adiv` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.garantiav` 	 	bit 		NOT NULL 	COMMENT,
	`ambart.bt.preclote`	bit 		NOT NULL 	COMMENT,
	`ambart.art.desiv` 		bit 		NOT NULL 	COMMENT,
	`ambart.imagen1v` 		bit 		NOT NULL 	COMMENT,
	`ambart.imagen2v` 		bit 		NOT NULL 	COMMENT,
	`ambart.primaria`		char(06) 	NOT NULL 	COMMENT,
	`ambart.secundaria`		char(06) 	NOT NULL 	COMMENT,
	`ambart.alterna`		char(06) 	NOT NULL 	COMMENT,
	`ambart.equi.pri` 		double  	NOT NULL 	COMMENT,
	`ambart.equi.sec` 		double  	NOT NULL 	COMMENT,
	`ambart.equi.alt` 		double  	NOT NULL 	COMMENT,
	`ambart.uni.relac1` 	double  	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambart.amb.usua`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Articulos-Productos`;


DROP TABLE IF EXISTS `dynerp.ambcierre`;

CREATE TABLE `dynerp.ambcierre` (
	`ambcierre.amb.usua` 	char(06)	NOT NULL 	COMMENT,
	`ambcierre.ent.num` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.almacen` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.almacend` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.co.alma` 	char(06) 	NOT NULL 	COMMENT,
	`ambcierre.bt.serial`	bit 		NOT NULL 	COMMENT,
	`ambcierre.bt.anulo` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.bt.reversa` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.fecha` 		bit 		NOT NULL 	COMMENT,
	`ambcierre.bt.confirm` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.odp.num` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.ent.des` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.bt.decon` 	bit 		NOT NULL 	COMMENT,
	`ambcierre.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo2` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo3` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo5` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo6` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo7` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.campo8` 		char(30) 	NOT NULL 	COMMENT,
	`ambcierre.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`ambcierre.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`ambcierre.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`ambcierre.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`ambcierre.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`ambcierre.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`ambcierre.trasnfe` 	char(01) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambcierre.amb.usua`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Cierre de Inventario`;



DROP TABLE IF EXISTS `dynerp.ambclpro`;

CREATE TABLE `dynerp.ambclpro` (
	`ambclpro.amb.usua` 	char(06) 	NOT NULL 	COMMENT,
	`ambclpro.tipo.cyp` 	char(01) 	NOT NULL 	COMMENT,
	`ambclpro.co.cliv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipod`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.tipov`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.cli.desv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.direc1v`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.direc2v`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.telefonosv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.faxv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.inactivov`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.comentariv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.responsv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.fecha.regv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.saldov`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.mont.crev`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.plaz.pagv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.descppagov`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.con.zond`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.zonv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.zon` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.co.segd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.segv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.seg` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.con.vend` 	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.venv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.ven` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.desc.globv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.horarcajav`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.frecuvistv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.lunesv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.martesv` 	 	bit 		NOT NULL 	COMMENT,
	`ambclpro.miercolesv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.juevesv` 	 	bit 		NOT NULL 	COMMENT,
	`ambclpro.viernesv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.sabadov` 	 	bit 		NOT NULL 	COMMENT,
	`ambclpro.domingov`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.dir.ent2v`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.rifv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.contribuv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.dis.cenv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.nitv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.emailv` 	 	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.ingrd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.ingrv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.ingr` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.tipo.perd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo.perv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo.per`		char(01) 	NOT NULL 	COMMENT,
	`ambclpro.co.tabv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo.adid`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo.adiv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.tipo.adi` 	int 		NOT NULL 	COMMENT,
	`ambclpro.matrizd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.matrizv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.matriz` 		char(10) 	NOT NULL 	COMMENT,
	`ambclpro.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo2` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo3` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo5` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo6` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo7` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.campo8` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`ambclpro.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`ambclpro.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`ambclpro.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`ambclpro.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`ambclpro.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`ambclpro.revisado` 	char(01) 	NOT NULL 	COMMENT,
	`ambclpro.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`ambclpro.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.serialp` 		char(30) 	NOT NULL 	COMMENT,
	`ambclpro.valido`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.loginv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.passwordv` 	bit 		NOT NULL 	COMMENT,
	`ambclpro.estadov`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.vpasswordv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.paisv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.paisd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.co.pais` 		char(06) 	NOT NULL 	COMMENT,
	`ambclpro.zipv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.ciudadv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.TaxIDv`  		bit 		NOT NULL 	COMMENT,
	`ambclpro.FormTypev`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.FormTyped`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.FormType` 	char(30) 	NOT NULL 	COMMENT,
	`ambclpro.WebSitev`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.BWebSitev`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.Bemailv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.salestaxv`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.salestaxd`  	bit 		NOT NULL 	COMMENT,
	`ambclpro.salestax` 	char(08) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambclpro.amb.usua, ambclpro.tipo.cyp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Cierre de Inventario`;


DROP TABLE IF EXISTS `dynerp.ambdev`;

CREATE TABLE `dynerp.ambdev` (
	`ambdev.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.almaori` 	 	bit 		NOT NULL 	COMMENT,
	`ambdev.almorid` 	 	bit 		NOT NULL 	COMMENT,
	`ambdev.alma.ori`		char(06) 	NOT NULL 	COMMENT,
	`ambdev.almades`  		bit 		NOT NULL 	COMMENT,
	`ambdev.almdesd` 	 	bit 		NOT NULL 	COMMENT,
	`ambdev.alma.des`	 	char(06) 	NOT NULL 	COMMENT,
	`ambdev.fecha`  		bit 		NOT NULL 	COMMENT,
	`ambdev.motivo`  		bit 		NOT NULL 	COMMENT,
	`ambdev.bt.ser`  		bit 		NOT NULL 	COMMENT,
	`ambdev.bt.anula` 	 	bit 		NOT NULL 	COMMENT,
	`ambdev.bt.reversa`		bit 		NOT NULL 	COMMENT,
	`ambdev.confirma`  		bit 		NOT NULL 	COMMENT,
	`ambdev.desconfima`  	bit 		NOT NULL 	COMMENT,
	`ambdev.stock.neg`  	bit 		NOT NULL 	COMMENT,
	`ambdev.pstock.neg`  	bit 		NOT NULL 	COMMENT,
	`ambdev.campo1` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo2` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo3` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo4` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo5` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo6` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo7` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.campo8` 		char(60) 	NOT NULL 	COMMENT,
	`ambdev.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.plotefec`  		bit 		NOT NULL 	COMMENT,
	`ambdev.dev.num`  		bit 		NOT NULL 	COMMENT,
	`ambdev.devolver`  		bit 		NOT NULL 	COMMENT,
	`ambdev.odp.num`  		bit 		NOT NULL 	COMMENT,
	`ambdev.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambdev.amb.usua, ambclpro.tipo.cyp`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Cierre de Inventario`;



DROP TABLE IF EXISTS `dynerp.ambemp`;

CREATE TABLE `dynerp.ambemp` (
	`ambemp.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambemp.num.emp` 		bit 		NOT NULL 	COMMENT,
	`ambemp.fecha` 			bit 		NOT NULL 	COMMENT,
	`ambemp.tipo.doc` 		bit 		NOT NULL 	COMMENT,
	`ambemp.nro.orig` 		bit 		NOT NULL 	COMMENT,
	`ambemp.descrip` 		bit 		NOT NULL 	COMMENT,
	`ambemp.camp.adi` 		bit 		NOT NULL 	COMMENT,
	`ambemp.unid` 			bit 		NOT NULL 	COMMENT,
	`ambemp.bulto` 			bit 		NOT NULL 	COMMENT,
	`ambemp.agrupar` 		bit 		NOT NULL 	COMMENT,
	`ambemp.reempaq` 		bit 		NOT NULL 	COMMENT,
	`ambemp.factura` 		bit 		NOT NULL 	COMMENT,
	`ambemp.canti` 			bit 		NOT NULL 	COMMENT,
	`ambemp.canti.d` 		bit 		NOT NULL 	COMMENT,
	`ambemp.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambemp.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambemp.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambemp.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambemp.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambemp.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambemp.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambemp.campo1` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo2` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo3` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo4`			varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo5` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo6` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo7` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.campo8` 		varchar(60) NOT NULL 	COMMENT,
	`ambemp.tipo.d` 		bit 		NOT NULL 	COMMENT,
	`ambemp.anular` 		bit 		NOT NULL 	COMMENT,
	`ambemp.dtipodoc` 		char(05) 	NOT NULL 	COMMENT,
	`ambemp.dcanti` 		double 		NOT NULL 	COMMENT,
	`ambemp.reng.s` 		bit 		NOT NULL 	COMMENT,
	`ambemp.revisado` 		char(01) 	NOT NULL 	COMMENT,
	`ambemp.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`ambemp.reng.c` 		bit 		NOT NULL 	COMMENT,
	`ambemp.coincide` 		bit 		NOT NULL 	COMMENT,
	`ambemp.envio` 			bit 		NOT NULL 	COMMENT,
	`ambemp.recibido` 		bit 		NOT NULL 	COMMENT,
	`ambemp.empacado` 		bit 		NOT NULL 	COMMENT,
	`ambemp.alma.d` 		bit 		NOT NULL 	COMMENT,
	`ambemp.alma` 			bit 		NOT NULL 	COMMENT,
	`ambemp.dalma` 			char(06) 	NOT NULL 	COMMENT,
	`ambemp.empr`			bit 		NOT NULL 	COMMENT,
	`ambemp.finalizar` 		bit 		NOT NULL 	COMMENT,
 	PRIMARY KEY (`ambemp.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;

	
DROP TABLE IF EXISTS `dynerp.ambentre`;

CREATE TABLE `dynerp.ambentre` (
	`ambentre.amb.usua` 	char(06) 	NOT NULL 	COMMENT,
	`ambentre.ent.num` 		bit 		NOT NULL 	COMMENT,
	`ambentre.almacen` 		bit 		NOT NULL 	COMMENT,
	`ambentre.almacend` 	bit 		NOT NULL 	COMMENT,
	`ambentre.co.alma` 		char(06) 	NOT NULL 	COMMENT,
	`ambentre.bt.serial` 	bit 		NOT NULL 	COMMENT,
	`ambentre.bt.anulo` 	bit 		NOT NULL 	COMMENT,
	`ambentre.bt.reversa` 	bit 		NOT NULL 	COMMENT,
	`ambentre.fecha` 		bit 		NOT NULL 	COMMENT,
	`ambentre.bt.confirm` 	bit 		NOT NULL 	COMMENT,
	`ambentre.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo2` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo3` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo5` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo6` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo7` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.campo8` 		char(30) 	NOT NULL 	COMMENT,
	`ambentre.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`ambentre.co.es.mo` 	char(06) 	NOT NULL 	COMMENT,
	`ambentre.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`ambentre.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`ambentre.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`ambentre.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`ambentre.odp.num` 		bit 		NOT NULL 	COMMENT,
	`ambentre.ent.des` 		bit 		NOT NULL 	COMMENT,
	`ambentre.bt.decon` 	bit 		NOT NULL 	COMMENT,
	`ambentre.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambentre.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.amblcobr`;

CREATE TABLE `dynerp.amblcobr` (
	`amblcobr.ambusu` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.amb.blco` 	char(01) 	NOT NULL 	COMMENT,
	`amblcobr.cob.num` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.recibo` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vco.cli` 		char(10) 	NOT NULL 	COMMENT,
	`amblcobr.dco.cli` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.co.cli` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vco.ven` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.dco.ven` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.co.ven` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.fec.con` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.monto.abo` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.dxpp` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.reten` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vtipo.cob` 	char(04) 	NOT NULL 	COMMENT,
	`amblcobr.dtipo.cob` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.tipo.cob` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.num.doc` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vtarjeta` 	char(06) 	NOT NULL 	COMMENT,
	`amblcobr.dtarjeta` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.tarjeta` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vcuenta` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.dcuenta` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.cuenta` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vbanco` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.dbanco` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.banco` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.fec.cheque` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.vcaja` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.dcaja` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.caja` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.monto.total` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.actual` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.cancelar` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.cheque` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.pago` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.reverso` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.despacho` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.facturas` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.caja` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.camb` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.tasa` 		double 		NOT NULL 	COMMENT,
	`amblcobr.dmoneda` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.moneda` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.vmoneda` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.p.abrir.ca` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.p.detal` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.campo1` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo2` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo3` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo4` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo5` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo6` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo7` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.campo8` 		varchar(60) NOT NULL 	COMMENT,
	`amblcobr.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`amblcobr.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`amblcobr.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`amblcobr.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`amblcobr.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`amblcobr.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`amblcobr.revisado` 	char(01) 	NOT NULL 	COMMENT,
	`amblcobr.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`amblcobr.p.para1` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.p.para2` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.p.para3` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.p.para4` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.p.para5` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`amblcobr.edppago` 		bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.reactiva` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.bt.anulado` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.des.crip` 	bit 		NOT NULL 	COMMENT,
	`amblcobr.mx.per` 		double 		NOT NULL 	COMMENT,
	`amblcobr.permodret` 	bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`amblcobr.ambusu`, `amblcobr.amb.blco`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.amblfact`;

CREATE TABLE `dynerp.amblfact` (
	`amblfact.amb.usua` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.amb.blfa` 	char(04) 	NOT NULL 	COMMENT,
	`amblfact.fact.num` 	bit 		NOT NULL 	COMMENT,
	`amblfact.contrib` 		bit 		NOT NULL 	COMMENT,
	`amblfact.descrip`		bit 		NOT NULL 	COMMENT,
	`amblfact.fec.emis` 	bit 		NOT NULL 	COMMENT,
	`amblfact.fec.venc` 	bit 		NOT NULL 	COMMENT,
	`amblfact.vco.cli` 		char(10) 	NOT NULL 	COMMENT,
	`amblfact.dco.cli` 		bit 		NOT NULL 	COMMENT,
	`amblfact.co.cli` 		bit 		NOT NULL 	COMMENT,
	`amblfact.vco.ven` 		char(06) 	NOT NULL 	COMMENT,
	`amblfact.dco.ven` 		bit 		NOT NULL 	COMMENT,
	`amblfact.co.ven` 		bit 		NOT NULL 	COMMENT,
	`amblfact.vco.tran` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.dco.tran` 	bit 		NOT NULL 	COMMENT,
	`amblfact.co.tran` 		bit 		NOT NULL 	COMMENT,
	`amblfact.vforma.pag` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.dforma.pag` 	bit 		NOT NULL 	COMMENT,
	`amblfact.forma.pag` 	bit 		NOT NULL 	COMMENT,
	`amblfact.vmoneda` 		char(06) 	NOT NULL 	COMMENT,
	`amblfact.dmoneda` 		bit 		NOT NULL 	COMMENT,
	`amblfact.moneda` 		bit 		NOT NULL 	COMMENT,
	`amblfact.monto.adi` 	bit 		NOT NULL 	COMMENT,
	`amblfact.com.relac` 	bit 		NOT NULL 	COMMENT,
	`amblfact.porc.gdesc` 	bit 		NOT NULL 	COMMENT,
	`amblfact.porc.reca` 	bit 		NOT NULL 	COMMENT,
	`amblfact.tot.flete`	bit 		NOT NULL 	COMMENT,
	`amblfact.stock.neg` 	bit 		NOT NULL 	COMMENT,
	`amblfact.cobrar.aut` 	bit 		NOT NULL 	COMMENT,
	`amblfact.num.listar` 	int 		NOT NULL 	COMMENT,
	`amblfact.listar` 		int 		NOT NULL 	COMMENT,
	`amblfact.pstock.neg` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pc1` 			bit 		NOT NULL 	COMMENT,
	`amblfact.pc2` 			bit 		NOT NULL 	COMMENT,
	`amblfact.pc3`			bit 		NOT NULL 	COMMENT,
	`amblfact.pc4`			bit 		NOT NULL 	COMMENT,
	`amblfact.pc5` 			bit 		NOT NULL 	COMMENT,
	`amblfact.saldo` 		bit 		NOT NULL 	COMMENT,
	`amblfact.fvenc` 		bit 		NOT NULL 	COMMENT,
	`amblfact.chdev` 		bit 		NOT NULL 	COMMENT,
	`amblfact.numcopia` 	int 		NOT NULL 	COMMENT,
	`amblfact.vreng.4` 		double 		NOT NULL 	COMMENT,
	`amblfact.dreng.4` 		bit 		NOT NULL 	COMMENT,
	`amblfact.vsucursal` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.vreng.3` 		char(06) 	NOT NULL 	COMMENT,
	`amblfact.dreng.3` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.3` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.4`		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.5`		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.6` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.7` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.8` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.9` 		bit 		NOT NULL 	COMMENT,
	`amblfact.reng.10` 		bit 		NOT NULL 	COMMENT,
	`amblfact.b.cobrar` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.importar` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.anular` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.seriales` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.notas` 		bit 		NOT NULL 	COMMENT,
	`amblfact.b.margen` 	bit 		NOT NULL 	COMMENT,
	`amblfact.p.margen` 	int 		NOT NULL 	COMMENT,
	`amblfact.b.clien` 		bit 		NOT NULL 	COMMENT,
	`amblfact.b.fact` 		bit 		NOT NULL 	COMMENT,
	`amblfact.tamcol01` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol02` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol03` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol04` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol05` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol06` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol07` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol08` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol09` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol10` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol11` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol12` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol13` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol14` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol15` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol16` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol17` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol18` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol19` 	int 		NOT NULL 	COMMENT,
	`amblfact.tamcol20` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol01` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol02` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol03` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol04` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol05` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol06` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol07` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol08` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol09` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol10`	 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol11` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol12` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol13` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol14` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol15` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol16` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol17` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol18` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol19` 	int 		NOT NULL 	COMMENT,
	`amblfact.poscol20` 	int 		NOT NULL 	COMMENT,
	`amblfact.campo1` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo2` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo3` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo4` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo5` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo6` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo7` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.campo8` 		varchar(60)	NOT NULL 	COMMENT,
	`amblfact.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`amblfact.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`amblfact.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`amblfact.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`amblfact.revisado`	 	char(01) 	NOT NULL 	COMMENT,
	`amblfact.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`amblfact.p.para1` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para2` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para3` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para4` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para5` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para6` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para7` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para8` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para9` 		bit 		NOT NULL 	COMMENT,
	`amblfact.p.para10` 	bit 		NOT NULL 	COMMENT,
	`amblfact.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`amblfact.b.reactivar` 	bit 		NOT NULL 	COMMENT,
	`amblfact.p.dev.reng` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.art` 		bit 		NOT NULL 	COMMENT,
	`amblfact.b.devdinero` 	bit 		NOT NULL 	COMMENT,
	`amblfact.b.revdinero` 	bit 		NOT NULL 	COMMENT,
	`amblfact.p.lotefec` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.1` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.2` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.3` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.4` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.5` 	bit 		NOT NULL 	COMMENT,
	`amblfact.SERIE` 		int 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.6` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.7`	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.8` 	bit 		NOT NULL 	COMMENT,
	`amblfact.pcontrol.9` 	bit 		NOT NULL 	COMMENT,
	`amblfact.Tax` 			bit 		NOT NULL 	COMMENT,
	`amblfact.vtax` 		char(08) 	NOT NULL 	COMMENT,
	`amblfact.dtax` 		bit 		NOT NULL 	COMMENT,
	`amblfact.numcontrol` 	bit 		NOT NULL 	COMMENT,
	`amblfact.actforma` 	bit 		NOT NULL 	COMMENT,
	`amblfact.formapag` 	varchar(01) NOT NULL 	COMMENT,
	`amblfact.man.impr` 	bit 		NOT NULL 	COMMENT,
	`amblfact.serial.lleno` bit 		NOT NULL 	COMMENT,
	`amblfact.des.fac` 		bit 		NOT NULL 	COMMENT,
	`amblfact.rein.art` 	bit 		NOT NULL 	COMMENT,
	`amblfact.maxefec` 		double 		NOT NULL 	COMMENT,
	`amblfact.pimpfac` 		bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`amblfact.amb.usua`, `amblfact.amb.blfa`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.ambmov`;

CREATE TABLE `dynerp.ambmov` (
	`ambmov.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.tipo.movi` 		char(01) 	NOT NULL 	COMMENT,
	`ambmov.mov.numv` 		bit 		NOT NULL 	COMMENT,
	`ambmov.codigov` 		bit 		NOT NULL 	COMMENT,
	`ambmov.codigod` 		bit 		NOT NULL 	COMMENT,
	`ambmov.codigo` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.tipo.opv` 		bit 		NOT NULL 	COMMENT,
	`ambmov.tipo.opd` 		bit 		NOT NULL 	COMMENT,
	`ambmov.tipo.op` 		char(02) NOT NULL,
	`ambmov.forma.pagv` 	bit 		NOT NULL 	COMMENT,
	`ambmov.forma.pagd` 	bit 		NOT NULL 	COMMENT,
	`ambmov.forma.pag` 		char(02) NOT NULL,
	`ambmov.fechav` 		bit 		NOT NULL 	COMMENT,
	`ambmov.doc.numv` 		bit 		NOT NULL 	COMMENT,
	`ambmov.descripv` 		bit 		NOT NULL 	COMMENT,
	`ambmov.montov` 		bit 		NOT NULL 	COMMENT,
	`ambmov.cta.egrev` 		bit 		NOT NULL 	COMMENT,
	`ambmov.cta.egred` 		bit 		NOT NULL 	COMMENT,
	`ambmov.cta.egre` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.banc.tarjv` 	bit 		NOT NULL 	COMMENT,
	`ambmov.banc.tarjd` 	bit 		NOT NULL 	COMMENT,
	`ambmov.banc.tarj` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.bt.reverv` 		bit 		NOT NULL 	COMMENT,
	`ambmov.bt.anulav` 		bit 		NOT NULL 	COMMENT,
	`ambmov.tasav` 			bit 		NOT NULL 	COMMENT,
	`ambmov.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambmov.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambmov.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambmov.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambmov.revisado` 		char(01) 	NOT NULL 	COMMENT,
	`ambmov.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`ambmov.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambmov.amb.usua`, `ambmov.tipo.movi`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.ambdev`;

CREATE TABLE `dynerp.ambdev` (
	`ambdev.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.monum.odp` 		bit 		NOT NULL 	COMMENT,
	`ambdev.mopriorid`		bit 		NOT NULL 	COMMENT,
	`ambdev.prioridad` 		bit 		NOT NULL 	COMMENT,
	`ambdev.vaprioridad` 	int 		NOT NULL 	COMMENT,
	`ambdev.mofe.emis` 		bit 		NOT NULL 	COMMENT,
	`ambdev.mofe.inic` 		bit 		NOT NULL 	COMMENT,
	`ambdev.mofe.fad` 		bit 		NOT NULL 	COMMENT,
	`ambdev.moco.ced` 		bit 		NOT NULL 	COMMENT,
	`ambdev.bt.anulo` 		bit 		NOT NULL 	COMMENT,
	`ambdev.bt.reversa` 	bit 		NOT NULL 	COMMENT,
	`ambdev.importar` 		bit 		NOT NULL 	COMMENT,
	`ambdev.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo2` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo3` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo5` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo6` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo7` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.campo8` 		char(30) 	NOT NULL 	COMMENT,
	`ambdev.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambdev.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambdev.modi.op` 		bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`ambdev.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.ambordpa`;

CREATE TABLE `dynerp.ambordpa` (
	`ambordpa.amb.usua` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.orden.num` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.fechav` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.bend` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.benv` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.ben` 		char(10) 	NOT NULL 	COMMENT,
	`ambordpa.forma.pagd` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.forma.pagv` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.forma.pag` 	char(02) NOT NULL,
	`ambordpa.montov` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.tipo.impd` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.tipo.impv` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.tipo.imp` 	char(01) 	NOT NULL 	COMMENT,
	`ambordpa.fec.pagv` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.ctad` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.ctav` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.cta` 		char(06) 	NOT NULL 	COMMENT,
	`ambordpa.chequev` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.cajad` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.cajav` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cod.caja` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.islrv` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.cta.egred` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cta.egrev` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.cta.egre` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.tasav` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.monedad` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.monedav` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.moneda` 		char(06) 	NOT NULL 	COMMENT,
	`ambordpa.campo1` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo2` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo3` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo4` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo5` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo6` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo7` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.campo8` 		varchar(60) NOT NULL 	COMMENT,
	`ambordpa.co.us.ad` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.fe.us.ad` 	datetime 	NOT NULL 	COMMENT,
	`ambordpa.co.us.mo` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.fe.us.mo` 	datetime 	NOT NULL 	COMMENT,
	`ambordpa.co.us.el` 	char(06) 	NOT NULL 	COMMENT,
	`ambordpa.fe.us.el` 	datetime 	NOT NULL 	COMMENT,
	`ambordpa.revisado` 	char(01) 	NOT NULL 	COMMENT,
	`ambordpa.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`ambordpa.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambordpa.impriv` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.pago1v` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.pago2v` 		bit 		NOT NULL 	COMMENT,
	`ambordpa.detallev` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.descripv` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.bt.anular` 	bit 		NOT NULL 	COMMENT,
	`ambordpa.bt.reactivar` bit 		NOT NULL 	COMMENT,
	`ambordpa.permodret` 	bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`ambordpa.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;

DROP TABLE IF EXISTS `dynerp.ambpar`;
CREATE TABLE `dynerp.ambpar` (	
	`ambpar.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambpar.falla.num` 		bit 		NOT NULL 	COMMENT,
	`ambpar.falla.fut` 		bit 		NOT NULL 	COMMENT,
	`ambpar.campo1` 		char(30) 	NOT NULL 	COMMENT,
	`ambpar.campo2` 		char(30) 	NOT NULL 	COMMENT,
	`ambpar.campo3` 		char(30) 	NOT NULL 	COMMENT,
	`ambpar.campo4` 		char(30) 	NOT NULL 	COMMENT,
	`ambpar.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambpar.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambpar.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambpar.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambpar.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambpar.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambpar.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambpar.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.ambreq`;

CREATE TABLE `dynerp.ambreq` (
	`ambreq.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.odp.num` 		bit 		NOT NULL 	COMMENT,
	`ambreq.almaori` 		bit 		NOT NULL 	COMMENT,
	`ambreq.almorid` 		bit 		NOT NULL 	COMMENT,
	`ambreq.alma.ori` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.almades` 		bit 		NOT NULL 	COMMENT,
	`ambreq.almdesd` 		bit 		NOT NULL 	COMMENT,
	`ambreq.alma.des` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.fecha` 			bit 		NOT NULL 	COMMENT,
	`ambreq.motivo` 		bit 		NOT NULL 	COMMENT,
	`ambreq.bt.ser` 		bit 		NOT NULL 	COMMENT,
	`ambreq.bt.anula` 		bit 		NOT NULL 	COMMENT,
	`ambreq.bt.reversa` 	bit 		NOT NULL 	COMMENT,
	`ambreq.confirma` 		bit 		NOT NULL 	COMMENT,
	`ambreq.desconfima` 	bit 		NOT NULL 	COMMENT,
	`ambreq.stock.neg` 		bit 		NOT NULL 	COMMENT,
	`ambreq.pstock.neg` 	bit 		NOT NULL 	COMMENT,
	`ambreq.campo1` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo2` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo3` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo4` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo5` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo6` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo7` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.campo8` 		char(60) 	NOT NULL 	COMMENT,
	`ambreq.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambreq.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambreq.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambreq.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambreq.p.lotefec` 		bit 		NOT NULL 	COMMENT,
	`ambreq.req.num`		bit 		NOT NULL 	COMMENT,
	`ambreq.solicitar` 		bit 		NOT NULL 	COMMENT,
	`ambreq.entregar` 		bit 		NOT NULL 	COMMENT,
	`ambreq.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ambreq.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.ambtras`;

CREATE TABLE `dynerp.ambtras` (
	`ambtras.amb.usua` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.tras.num` 		bit 		NOT NULL 	COMMENT,
	`ambtras.almaori` 		bit 		NOT NULL 	COMMENT,
	`ambtras.almorid` 		bit 		NOT NULL 	COMMENT,
	`ambtras.alma.ori` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.almades` 		bit 		NOT NULL 	COMMENT,
	`ambtras.almdesd` 		bit 		NOT NULL 	COMMENT,
	`ambtras.alma.des` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.fecha` 		bit 		NOT NULL 	COMMENT,
	`ambtras.motivo` 		bit 		NOT NULL 	COMMENT,
	`ambtras.bt.ser` 		bit 		NOT NULL 	COMMENT,
	`ambtras.bt.anula` 		bit 		NOT NULL 	COMMENT,
	`ambtras.bt.reversa` 	bit 		NOT NULL 	COMMENT,
	`ambtras.confirma` 		bit 		NOT NULL 	COMMENT,
	`ambtras.desconfima` 	bit 		NOT NULL 	COMMENT,
	`ambtras.stock.neg` 	bit 		NOT NULL 	COMMENT,
	`ambtras.pstock.neg` 	bit 		NOT NULL 	COMMENT,
	`ambtras.campo1` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo2` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo3` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo4` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo5` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo6` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo7` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.campo8` 		varchar(60) 	NOT NULL 	COMMENT,
	`ambtras.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`ambtras.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`ambtras.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`ambtras.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`ambtras.p.lotefec` 	bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`ambtras.amb.usua`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.aranc`;

CREATE TABLE `dynerp.aranc` (
	`aranc.co.art` 			char(30) 	NOT NULL 	COMMENT,
	`aranc.co.ara` 			varchar(15) NOT NULL 	COMMENT,
	`aranc.des.ara` 		varchar(60) NOT NULL 	COMMENT,
	`aranc.porc.ara` 		double 		NOT NULL 	COMMENT,
	`aranc.calidad` 		char(01) 	NOT NULL 	COMMENT,
	`aranc.nivel` 			char(04) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`ajuste.ajue.num`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.art`;

CREATE TABLE `dynerp.art` (
	`art.cod.art` 			char(30) 	 NOT NULL 	COMMENT,
	`art.des.art` 			varchar(120) NOT NULL 	COMMENT,
	`art.fecha.reg` 		datetime 	 NOT NULL 	COMMENT,
	`art.manj.ser` 			bit 		 NOT NULL 	COMMENT,
	`art.co.lad` 			char(06) 	 NOT NULL 	COMMENT,
	`art.co.cat` 			char(06) 	 NOT NULL 	COMMENT,
	`art.co.subl` 			char(06) 	 NOT NULL 	COMMENT,
	`art.co.color` 			char(06) 	NOT NULL 	COMMENT,
	`art.item` 				char(10) 	NOT NULL 	COMMENT,
	`art.refer` 			char(20) 	NOT NULL 	COMMENT,
	`art.modelo` 			char(20) 	NOT NULL 	COMMENT,
	`art.procedenci` 		char(06) 	NOT NULL 	COMMENT,
	`art.comentario` 		text 		NOT NULL 	COMMENT,
	`art.co.prov` 			char(10) 	NOT NULL 	COMMENT,
	`art.ubicacion` 		varchar(60) 	NOT NULL 	COMMENT,
	`art.uni.venta` 		char(06) 	NOT NULL 	COMMENT,
	`art.uni.compra` 		char(06) 	NOT NULL 	COMMENT,
	`art.uni.relac` 		double 		NOT NULL 	COMMENT,
	`art.relac.aut` 		int 		NOT NULL 	COMMENT,
	`art.stock.act` 		double 		NOT NULL 	COMMENT,
	`art.stock.com` 		double 		NOT NULL 	COMMENT,
	`art.sstock.com` 		double 		NOT NULL 	COMMENT,
	`art.stock.lle` 		double 		NOT NULL 	COMMENT,
	`art.sstock.lle` 		double 		NOT NULL 	COMMENT,
	`art.stock.des` 		double 		NOT NULL 	COMMENT,
	`art.sstock.des` 		double 		NOT NULL 	COMMENT,
	`art.suni.venta` 		char(06) 	NOT NULL 	COMMENT,
	`art.suni.compr` 		char(06) 	NOT NULL 	COMMENT,
	`art.suni.relac` 		decimal(18,3) NOT NULL,
	`art.sstock.act` 		double 		NOT NULL 	COMMENT,
	`art.relac.comp` 		double 		NOT NULL 	COMMENT,
	`art.relac.vent` 		double 		NOT NULL 	COMMENT,
	`art.pto.pedido` 		double 		NOT NULL 	COMMENT,
	`art.stock.mx` 			double 		NOT NULL 	COMMENT,
	`art.stock.mad` 		double 		NOT NULL 	COMMENT,
	`art.prec.om` 			bit 		NOT NULL 	COMMENT,
	`art.prec.vta1` 		double 		NOT NULL 	COMMENT,
	`art.fec.prec.v`		datetime 	NOT NULL 	COMMENT,
	`art.fec.prec.2` 		datetime 	NOT NULL 	COMMENT,
	`art.prec.vta2` 		double 		NOT NULL 	COMMENT,
	`art.fec.prec.3` 		datetime 	NOT NULL 	COMMENT,
	`art.prec.vta3` 		double 		NOT NULL 	COMMENT,
	`art.fec.prec.4` 		datetime 	NOT NULL 	COMMENT,
	`art.prec.vta4` 		double 		NOT NULL 	COMMENT,
	`art.fec.prec.5` 		datetime 	NOT NULL 	COMMENT,
	`art.prec.vta5` 		double 		NOT NULL 	COMMENT,
	`art.prec.agr1` 		double 		NOT NULL 	COMMENT,
	`art.prec.agr2` 		double 		NOT NULL 	COMMENT,
	`art.prec.agr3` 		double 		NOT NULL 	COMMENT,
	`art.prec.agr4` 		double 		NOT NULL 	COMMENT,
	`art.prec.agr5` 		double 		NOT NULL 	COMMENT,
	`art.can.agr` 			double 		NOT NULL 	COMMENT,
	`art.fec.des.p5` 		datetime 	NOT NULL 	COMMENT,
	`art.fec.has.p5` 		datetime 	NOT NULL 	COMMENT,
	`art.co.imp` 			char(04) 	NOT NULL 	COMMENT,
	`art.margen.mx` 		double 		NOT NULL 	COMMENT,
	`art.ult.cto.un` 		double 		NOT NULL 	COMMENT,
	`art.fec.ult.co` 		datetime 	NOT NULL 	COMMENT,
	`art.cto.pro.un` 		double 		NOT NULL 	COMMENT,
	`art.fec.cto.pr` 		datetime 	NOT NULL 	COMMENT,
	`art.cto.merc` 			double 		NOT NULL 	COMMENT,
	`art.fec.cto.me` 		datetime 	NOT NULL 	COMMENT,
	`art.cto.prov` 			double 		NOT NULL 	COMMENT,
	`art.fec.cto.p2` 		datetime 	NOT NULL 	COMMENT,
	`art.ult.cto.dt` 		double 		NOT NULL 	COMMENT,
	`art.fec.cto.dt` 		datetime 	NOT NULL 	COMMENT,
	`art.cto.un.an` 		double 		NOT NULL 	COMMENT,
	`art.fec.cto.an` 		datetime 	NOT NULL 	COMMENT,
	`art.ult.cto.om` 		double 		NOT NULL 	COMMENT,
	`art.fec.ult.om` 		datetime 	NOT NULL 	COMMENT,
	`art.cto.pro.om` 		double 		NOT NULL 	COMMENT,
	`art.fec.pro.om` 		datetime 	NOT NULL 	COMMENT,
	`art.tipo.cto` 			char(04) 	NOT NULL 	COMMENT,
	`art.mont.comi` 		double 		NOT NULL 	COMMENT,
	`art.porc.cto` 			double 		NOT NULL 	COMMENT,
	`art.mont.cto` 			double 		NOT NULL 	COMMENT,
	`art.porc.gas` 			double 		NOT NULL 	COMMENT,
	`art.mont.gas` 			double 		NOT NULL 	COMMENT,
	`art.f.cost` 			datetime 	NOT NULL 	COMMENT,
	`art.fisico` 			bit 		NOT NULL 	COMMENT,
	`art.punt.cli` 			double 		NOT NULL 	COMMENT,
	`art.punt.pro` 			double 		NOT NULL 	COMMENT,
	`art.dias.repos` 		int 		NOT NULL 	COMMENT,
	`art.tipo` 				char(01) 	NOT NULL 	COMMENT,
	`art.alm.prad` 			char(04) 	NOT NULL 	COMMENT,
	`art.anulado` 			bit 		NOT NULL 	COMMENT,
	`art.tipo.imp` 			char(01) 	NOT NULL 	COMMENT,
	`art.dis.cen` 			text  		NOT NULL 	COMMENT,
	`art.mon.ilc` 			double 		NOT NULL 	COMMENT,
	`art.capacidad` 		decimal(18,3) DEFAULT	NOT NULL	COMMENT,
	`art.grado.al` 			decimal(10,2) DEFAULT	NOT NULL	COMMENT,
	`art.tipo.licor` 		char(01) 	NOT NULL 	COMMENT,
	`art.compuesto` 		bit 		NOT NULL 	COMMENT,
	`art.picture` 			varchar(60)	NOT NULL 	COMMENT,
	`art.campo1` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo2` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo3` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo4` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo5` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo6` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo7` 			varchar(60) NOT NULL 	COMMENT,
	`art.campo8` 			varchar(60) NOT NULL 	COMMENT,
	`art.co.us.ad` 			char(06) 	NOT NULL 	COMMENT,
	`art.fe.us.ad` 			datetime 	NOT NULL 	COMMENT,
	`art.co.us.mo` 			char(06) 	NOT NULL 	COMMENT,
	`art.fe.us.mo` 			datetime 	NOT NULL 	COMMENT,
	`art.co.us.el` 			char(06) 	NOT NULL 	COMMENT,
	`art.fe.us.el` 			datetime 	NOT NULL 	COMMENT,
	`art.revisado` 			char(01) 	NOT NULL 	COMMENT,
	`art.trasnfe` 			char(01) 	NOT NULL 	COMMENT,
	`art.co.sucu` 			char(06) 	NOT NULL 	COMMENT,
	`art.tuni.venta` 		char(06) 	NOT NULL 	COMMENT,
	`art.equi.uni1` 		double 		NOT NULL 	COMMENT,
	`art.equi.uni2` 		double 		NOT NULL 	COMMENT,
	`art.equi.uni3` 		double 		NOT NULL 	COMMENT,
	`art.lote` 				bit 		NOT NULL 	COMMENT,
	`art.serialp` 			char(30) 	NOT NULL 	COMMENT,
	`art.valido` 			bit 		NOT NULL 	COMMENT,
	`art.atributo1` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo1` 		char(15) 	NOT NULL 	COMMENT,
	`art.atributo2` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo2` 		char(15) 	NOT NULL 	COMMENT,
	`art.atributo3` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo3` 		char(15) 	NOT NULL 	COMMENT,
	`art.atributo4` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo4` 		char(15) 	NOT NULL 	COMMENT,
	`art.atributo5` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo5` 		char(15) 	NOT NULL 	COMMENT,
	`art.atributo6` 		bit 		NOT NULL 	COMMENT,
	`art.vatributo6` 		char(15) 	NOT NULL 	COMMENT,
	`art.garantia` 			char(30) 	NOT NULL 	COMMENT,
	`art.peso` 				double 		NOT NULL 	COMMENT,
	`art.pie` 				double 		NOT NULL 	COMMENT,
	`art.margen1` 			double 		NOT NULL 	COMMENT,
	`art.margen2` 			double 		NOT NULL 	COMMENT,
	`art.margen3` 			double 		NOT NULL 	COMMENT,
	`art.margen4` 			double 		NOT NULL 	COMMENT,
	`art.margen5` 			double 		NOT NULL 	COMMENT,
	`art.fila.id` 			timestamp 	NOT NULL 	COMMENT,
	`art.imagen1` 			varchar(60) NOT NULL 	COMMENT,
	`art.imagen2` 			varchar(60) NOT NULL 	COMMENT,
	`art.i.art.des` 		varchar(60) NOT NULL 	COMMENT,
	`art.uni.emp` 			char(06) 	NOT NULL 	COMMENT,
	`art.rel.emp` 			double 		NOT NULL 	COMMENT,
	`art.movil` 			bit 		NOT NULL 	COMMENT,
	PRIMARY KEY (`art.cod.art`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;

	
DROP TABLE IF EXISTS `dynerp.auxiliar`;

CREATE TABLE `dynerp.auxiliar` (
	`auxiliar.nom.aux` 		char(10) 	 NOT NULL 	DEFAULT (space(1)),
	`auxiliar.val.aux` 		varchar(254) NOT NULL 	DEFAULT (space(1)),
	`auxiliar.tipo.aux` 	char(01) 	 NOT NULL 	DEFAULT (space(1)),
	`auxiliar.form.aux` 	varchar(254) NOT NULL	DEFAULT (space(1)),
	`auxiliar.cach.aux` 	bit 		 NOT NULL 	DEFAULT ((0)),
	`auxiliar.grup.aux` 	char(16) 	 NOT NULL 	DEFAULT (space(1)),
	`auxiliar.des.aux` 		varchar(60)  NOT NULL 	DEFAULT (space(1)),
	PRIMARY KEY (`auxiliar.nom.aux, auxiliar.grup.aux`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.bancos`;

CREATE TABLE `dynerp.bancos` (
	`bancos.cod.ban` 		char(06) 	NOT NULL 	COMMENT,
	`bancos.des.ban` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.telefonos` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.campo1` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.campo2` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.campo3` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.campo4` 		varchar(60) NOT NULL 	COMMENT,
	`bancos.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`bancos.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`bancos.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`bancos.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`bancos.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`bancos.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`bancos.revisado` 		char(01) 	NOT NULL 	COMMENT,
	`bancos.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`bancos.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`bancos.plazo1` 		decimal(18,0) DEFAULT	NOT NULL 	COMMENT,
	`bancos.plazo2` 		decimal(18,0) DEFAULT	NOT NULL 	COMMENT,
	`bancos.plazo3` 		decimal(18,0) DEFAULT	NOT NULL 	COMMENT,
	`bancos.plazo4` 		decimal(18,0) DEFAULT	NOT NULL 	COMMENT,
	`bancos.fila.id` 		timestamp 	NOT NULL 	COMMENT,
	PRIMARY KEY (`bancos.cod.ban`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.benef`;

CREATE TABLE `dynerp.benef` (
	`benef.cod.ben` 		char(10) 	NOT NULL 	COMMENT,
	`benef.ben.des` 		varchar(60) NOT NULL 	COMMENT,
	`benef.rif` 			char(18) 	NOT NULL 	COMMENT,
	`benef.direc1` 			char(100) 	NOT NULL 	COMMENT,
	`benef.dis.cen` 		text 		NOT NULL 	COMMENT,
	`benef.telefono` 		varchar(60) NOT NULL 	COMMENT,
	`benef.campo1` 			varchar(60) NOT NULL 	COMMENT,
	`benef.campo2` 			varchar(60) NOT NULL 	COMMENT,
	`benef.campo3` 			varchar(60) NOT NULL 	COMMENT,
	`benef.campo4` 			varchar(60) NOT NULL 	COMMENT,
	`benef.co.us.ad` 		char(06) 	NOT NULL 	COMMENT,
	`benef.fe.us.ad` 		datetime 	NOT NULL 	COMMENT,
	`benef.co.us.mo` 		char(06) 	NOT NULL 	COMMENT,
	`benef.fe.us.mo` 		datetime 	NOT NULL 	COMMENT,
	`benef.co.us.el` 		char(06) 	NOT NULL 	COMMENT,
	`benef.fe.us.el` 		datetime 	NOT NULL 	COMMENT,
	`benef.revisado` 		char(01) 	NOT NULL 	COMMENT,
	`benef.trasnfe` 		char(01) 	NOT NULL 	COMMENT,
	`benef.co.sucu` 		char(06) 	NOT NULL 	COMMENT,
	`benef.tipo.per` 		char(01) 	NOT NULL 	COMMENT,
	`benef.CO.TAB` 			int 		NOT NULL 	COMMENT,
	`benef.nit` 			char(18) 	NOT NULL 	COMMENT,
	PRIMARY KEY (`benef.cod.ben`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.cajas`;

CREATE TABLE `dynerp.cajas` (
	`cajas.cod.caja` 	char(06) 		NOT NULL 	COMMENT,
	`cajas.descrip` 	varchar(60) 	NOT NULL 	COMMENT,
	`cajas.mes.ini` 	datetime 		NOT NULL 	COMMENT,
	`cajas.saldo.i` 	double 			NOT NULL 	COMMENT,
	`cajas.saldo.ei` 	double 			NOT NULL 	COMMENT,
	`cajas.saldo.a` 	double 			NOT NULL 	COMMENT,
	`cajas.saldo.e` 	double 			NOT NULL 	COMMENT,
	`cajas.moneda` 		char(06) 		NOT NULL 	COMMENT,
	`cajas.campo1` 		varchar(60) 	NOT NULL 	COMMENT,
	`cajas.campo2` 		varchar(60) 	NOT NULL 	COMMENT,
	`cajas.campo3` 		varchar(60) 	NOT NULL 	COMMENT,
	`cajas.campo4` 		varchar(60) 	NOT NULL 	COMMENT,
	`cajas.dis.cen` 	text 			DEFAULT		NOT NULL	COMMENT,
	`cajas.deb.ant` 	double	 		NOT NULL 	COMMENT,
	`cajas.hab.ant` 	double 			NOT NULL 	COMMENT,
	`cajas.co.us.ad` 	char(06) 		NOT NULL 	COMMENT,
	`cajas.fe.us.ad` 	datetime 		NOT NULL 	COMMENT,
	`cajas.co.us.mo` 	char(06)	 	NOT NULL 	COMMENT,
	`cajas.fe.us.mo` 	datetime	 	NOT NULL 	COMMENT,
	`cajas.co.us.el` 	char(06)	 	NOT NULL 	COMMENT,
	`cajas.fe.us.el` 	datetime	 	NOT NULL 	COMMENT,
	`cajas.revisado` 	char(01)	 	NOT NULL 	COMMENT,
	`cajas.trasnfe` 	char(01)	 	NOT NULL 	COMMENT,
	`cajas.co.sucu` 	char(06)	 	NOT NULL 	COMMENT,
	`cajas.inactivo` 	bit 			NOT NULL 	COMMENT,
	`cajas.gavetaser` 	bit 			NOT NULL 	COMMENT,
	`cajas.cajapri` 	bit 			NOT NULL 	COMMENT,
	`cajas.sidisplay` 	bit 			NOT NULL 	COMMENT,
	`cajas.puerto` 		char(01) 		NOT NULL 	COMMENT,
	`cajas.bitdatos` 	char(01) 		NOT NULL 	COMMENT,
	`cajas.bitstop` 	char(01) 		NOT NULL 	COMMENT,
	`cajas.paridad` 	char(01) 		NOT NULL 	COMMENT,
	`cajas.velocidad` 	char(05) 		NOT NULL 	COMMENT,
	`cajas.puerto2` 	char(01) 		NOT NULL 	COMMENT,
	`cajas.bitdatos2` 	char(01) 		NOT NULL 	COMMENT,
	`cajas.bitstop2` 	char(01)	 	NOT NULL 	COMMENT,
	`cajas.paridad2` 	char(01)	 	NOT NULL 	COMMENT,
	`cajas.gcadena` 	char(30)	 	NOT NULL 	COMMENT,
	`cajas.velocidad2` 	char(05)	 	NOT NULL 	COMMENT,
	`cajas.cajapvta` 	bit 			NOT NULL 	COMMENT,
	`cajas.mvisa` 		bit 			NOT NULL 	COMMENT,
	`cajas.vpostipo` 	int 			NOT NULL 	COMMENT,
	`cajas.impfis` 		char(20)	 	NOT NULL 	COMMENT,
	PRIMARY KEY (`cajas.cod.caja`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Ajustes en Facturas`;


DROP TABLE IF EXISTS `dynerp.catart`;

CREATE TABLE `dynerp.catart` (
	`catart.co.cat` 	char(06) 		NOT NULL 	COMMENT,
	`catart.cat.des` 	varchar(60) 	NOT NULL 	COMMENT,
	`catart.dis.cen` 	text 			NOT NULL 	COMMENT,
	`catart.campo1` 	varchar(60) 	NOT NULL 	COMMENT,
	`catart.campo2` 	varchar(60) 	NOT NULL 	COMMENT,
	`catart.campo3` 	varchar(60) 	NOT NULL 	COMMENT,
	`catart.campo4` 	varchar(60) 	NOT NULL 	COMMENT,
	`catart.co.us.ad` 	char(06) 		NOT NULL 	COMMENT,
	`catart.fe.us.ad` 	datetime 		NOT NULL 	COMMENT,
	`catart.co.us.mo` 	char(06) 		NOT NULL 	COMMENT,
	`catart.fe.us.mo` 	datetime 		NOT NULL 	COMMENT,
	`catart.co.us.el` 	char(06) 		NOT NULL 	COMMENT,
	`catart.fe.us.el` 	datetime 		NOT NULL 	COMMENT,
	`catart.revisado` 	char(01) 		NOT NULL 	COMMENT,
	`catart.trasnfe` 	char(01) 		NOT NULL 	COMMENT,
	`catart.co.sucu` 	char(06) 		NOT NULL 	COMMENT,
	`catart.co.imun` 	char(15) 		NOT NULL 	COMMENT,
	`catart.co.reten` 	char(06) 		NOT NULL 	COMMENT,
	`catart.row.id` 	timestamp 		NOT NULL 	COMMENT,
	`catart.movil` 		bit 			NOT NULL 	COMMENT,
	PRIMARY KEY (`catart.co.cat`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla de Catagoria de Articulos`;


DROP TABLE IF EXISTS `dynerp.chras`;

CREATE TABLE `dynerp.chras` 
	`chras.Co.Chra` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Chra.Des` 	varchar(60) 	NOT NULL 	COMMENT,
	`chras..cod.cta` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Fecha.Re` 	datetime 		NOT NULL 	COMMENT,
	`chras..Num.Ch.P` 	int 			NOT NULL 	COMMENT,
	`chras..Num.Ch.U` 	int 			NOT NULL 	COMMENT,
	`chras..Respons` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Campo1` 	varchar(60) 	NOT NULL 	COMMENT,
	`chras..Campo2` 	varchar(60) 	NOT NULL 	COMMENT,
	`chras..Campo3` 	varchar(60) 	NOT NULL 	COMMENT,
	`chras..Campo4` 	varchar(60) 	NOT NULL 	COMMENT,
	`chras..Co.Us.ad` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Fe.Us.ad` 	datetime 		NOT NULL 	COMMENT,
	`chras..Co.Us.Mo` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Fe.Us.Mo` 	datetime 		NOT NULL 	COMMENT,
	`chras..Co.Us.El` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Fe.Us.El` 	datetime 		NOT NULL 	COMMENT,
	`chras..Revisado` 	char(01) 		NOT NULL 	COMMENT,
	`chras..Trasnfe` 	char(01) 		NOT NULL 	COMMENT,
	`chras..Co.Sucu` 	char(06) 		NOT NULL 	COMMENT,
	`chras..Status` 	char(03) 		NOT NULL 	COMMENT,
	`chras..LimUsoRe` 	bit 			NOT NULL 	COMMENT,
	`chras..Ch.Gen` 	bit 			NOT NULL 	COMMENT,
	PRIMARY KEY (`chras.Co.Chra`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla Control de Chequeras`;


DROP TABLE IF EXISTS `dynerp.cheques`;

CREATE TABLE `dynerp.cheques` (
	`cheques.Co.Cheq` 	char(20) 		NOT NULL 	COMMENT,
	`cheques.Co.Chra` 	char(06) 		NOT NULL 	COMMENT,
	`cheques.Status` 	char(03) 		NOT NULL,
	`cheques.Monto` 	double 			NOT NULL 	COMMENT,
	`cheques.Descrip` 	varchar(60) 	NOT NULL 	COMMENT,
	`cheques.Fec.emis` 	datetime 		DEFAULT		NULL 							COMMENT,
	`cheques.Fec.ent` 	datetime 		DEFAULT		NULL 							COMMENT,
	`cheques.Entreg.a` 	varchar(60) 	NOT NULL 	COMMENT,
	`cheques.Coment` 	text 			NOT NULL 	COMMENT,
	`cheques.Co.Us.ad` 	char(06) 		NOT NULL 	COMMENT,
	`cheques.Fe.Us.ad` 	datetime 		NOT NULL 	COMMENT,
	`cheques.Co.Us.Mo` 	char(06) 		NOT NULL 	COMMENT,
	`cheques.Fe.Us.Mo` 	datetime 		NOT NULL 	COMMENT,
	`cheques.Co.Us.El` 	char(06) 		NOT NULL 	COMMENT,
	`cheques.Fe.Us.El` 	datetime 		NOT NULL 	COMMENT,
	`cheques.mov.num` 	int 			NOT NULL 	COMMENT,
	PRIMARY KEY (`cheques.Co.Cheq, cheques.Co.Chra`)
) 	ENGINE=InnoDB DEFAULT CHARSET=latin1 COMMENT=`Tabla control de Cheques`;
